### ISSUE TITLE
Better tools?

### ISSUE THREAD

**Issue by TapiaX** [motib/jbaci#2]
As you said there are better tools. Do you mind naming or linking to some of them? Also thanks I've learnt of jbaci in my OS course and I enjoy it.

**Comment by motib** [comment]
I am pleased that jbaci helped you. When jbaci was developed most languages did not support concurrency, but Java, Scala, Python, etc., do now, so you may not need a special tool. There might be modern tools that work at the low level like jBaci, but I have not worked in this area for many years and can't help.

**Comment by TapiaX** [comment]
Thanks for the quick reply, I'm closing it, maybe later I'll come up with names once I try some.
